name: validate
on:
  push:
    branches:
      - '+([0-9])?(.{+([0-9]),x}).x'
      - 'main'
      - 'next'
      - 'next-major'
      - 'beta'
      - 'alpha'
      - '!all-contributors/**'
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    # ignore all-contributors PRs
    if: ${{ !contains(github.head_ref, 'all-contributors') }}
    strategy:
      matrix:
        node: [20, 22, 24]
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v5

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: ▶️ Run validate script
        run: npm run validate

      - name: ⬆️ Upload coverage report
        uses: codecov/codecov-action@v5

  build-release-artifact:
    needs: main
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: ${{ github.repository == 'testing-library/cypress-testing-library' && github.event_name == 'push' }}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v5

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: 📥 Download deps
        run: npm install --ignore-scripts

      - name: 🏗 Run build script
        run: npm run build

      - name: 📦 Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-package-dist
          path: dist
          if-no-files-found: error
          retention-days: 7

  release:
    needs: build-release-artifact
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    if: ${{ github.repository == 'testing-library/cypress-testing-library' && github.event_name == 'push' }}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v5

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org/'

      - name: 📦 Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: npm-package-dist
          path: dist

      - name: 🚀 Release
        uses: cycjimmy/semantic-release-action@v5
        with:
          semantic_version: 25
          extra_plugins: |
            @semantic-release/npm@13
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              'next',
              'next-major',
              {name: 'beta', prerelease: true},
              {name: 'alpha', prerelease: true}
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
